In [87]:
import numpy as np
import h5py
import datetime
import pandas as pd

In [2]:
mat = scipy.io.loadmat('Dataset\wiki_crop\wiki.mat')

In [31]:
print( type(mat['wiki'] ) , mat['wiki'].shape )
print( type(mat['wiki'][0] ) , mat['wiki'][0].shape )
print( type(mat['wiki'][0][0]) , mat['wiki'][0][0].shape )
print( len(mat['wiki'][0][0]) , mat['wiki'][0][0] )

<class 'numpy.ndarray'> (1, 1)
<class 'numpy.ndarray'> (1,)
<class 'numpy.void'> ()
8 (array([[723671, 703186, 711677, ..., 720620, 723893, 713846]]), array([[2009, 1964, 2008, ..., 2013, 2011, 2008]], dtype=uint16), array([[array(['17/10000217_1981-05-05_2009.jpg'], dtype='<U31'),
        array(['48/10000548_1925-04-04_1964.jpg'], dtype='<U31'),
        array(['12/100012_1948-07-03_2008.jpg'], dtype='<U29'), ...,
        array(['09/9998109_1972-12-27_2013.jpg'], dtype='<U30'),
        array(['00/9999400_1981-12-13_2011.jpg'], dtype='<U30'),
        array(['80/999980_1954-06-11_2008.jpg'], dtype='<U29')]],
      dtype=object), array([[1., 1., 1., ..., 1., 1., 0.]]), array([[array(['Sami Jauhojärvi'], dtype='<U15'),
        array(['Dettmar Cramer'], dtype='<U14'),
        array(['Marc Okrand'], dtype='<U11'), ...,
        array(['Michael Wiesinger'], dtype='<U17'),
        array(['Johann Grugger'], dtype='<U14'),
        array(['Greta Van Susteren'], dtype='<U18')]], dtype=object), arra

In [41]:
print( mat['wiki'][0][0][0][0] ) # dob: date of birth (Matlab serial date number)
print( mat['wiki'][0][0][1] ) # photo_taken: year when the photo was taken
print( mat['wiki'][0][0][2] ) # full_path: path to file
print( mat['wiki'][0][0][3] ) # gender: 0 for female and 1 for male, NaN if unknown
print( mat['wiki'][0][0][4] ) # name: name of the celebrity
print( mat['wiki'][0][0][5] ) # face_location: location of the face. To crop the face in Matlab run
print( mat['wiki'][0][0][6] ) # face_score: detector score (the higher the better). Inf implies that no face was found in the image and the face_location then just returns the entire image
print( mat['wiki'][0][0][7] ) # second_face_score: detector score of the face with the second highest score. This is useful to ignore images with more than one face. second_face_score is NaN if no second face was detected.

[723671 703186 711677 ... 720620 723893 713846]
[[2009 1964 2008 ... 2013 2011 2008]]
[[array(['17/10000217_1981-05-05_2009.jpg'], dtype='<U31')
  array(['48/10000548_1925-04-04_1964.jpg'], dtype='<U31')
  array(['12/100012_1948-07-03_2008.jpg'], dtype='<U29') ...
  array(['09/9998109_1972-12-27_2013.jpg'], dtype='<U30')
  array(['00/9999400_1981-12-13_2011.jpg'], dtype='<U30')
  array(['80/999980_1954-06-11_2008.jpg'], dtype='<U29')]]
[[1. 1. 1. ... 1. 1. 0.]]
[[array(['Sami Jauhojärvi'], dtype='<U15')
  array(['Dettmar Cramer'], dtype='<U14')
  array(['Marc Okrand'], dtype='<U11') ...
  array(['Michael Wiesinger'], dtype='<U17')
  array(['Johann Grugger'], dtype='<U14')
  array(['Greta Van Susteren'], dtype='<U18')]]
[[array([[111.29109473, 111.29109473, 252.66993082, 252.66993082]])
  array([[252.4833023 , 126.68165115, 354.53192596, 228.73027481]])
  array([[113.52, 169.84, 366.08, 422.4 ]]) ...
  array([[169.88839786,  74.31669472, 235.2534231 , 139.68171997]])
  array([[1, 1, 1, 

In [57]:
python_datetime = datetime.date.fromordinal(int(mat['wiki'][0][0][0][0][0])) + datetime.timedelta(days=int(mat['wiki'][0][0][0][0][0])%1) - datetime.timedelta(days = 366)

In [58]:
python_datetime

datetime.date(1981, 5, 5)

In [61]:
python_datetime = datetime.date.fromordinal(int(mat['wiki'][0][0][0][0][1])) + datetime.timedelta(days=int(mat['wiki'][0][0][0][0][1])%1) - datetime.timedelta(days = 366)
python_datetime

datetime.date(1925, 4, 4)

In [ ]:
print( mat['wiki'][0][0][0][0] ) # dob: date of birth (Matlab serial date number)
print( mat['wiki'][0][0][1] ) # photo_taken: year when the photo was taken
print( mat['wiki'][0][0][2] ) # full_path: path to file
print( mat['wiki'][0][0][3] ) # gender: 0 for female and 1 for male, NaN if unknown
print( mat['wiki'][0][0][4] ) # name: name of the celebrity
print( mat['wiki'][0][0][5] ) # face_location: location of the face. To crop the face in Matlab run
print( mat['wiki'][0][0][6] ) # face_score: detector score (the higher the better). Inf implies that no face was found in the image and the face_location then just returns the entire image
print( mat['wiki'][0][0][7] ) # second_face_score: detector score of the face with the second highest score. This is useful to ignore images with more than one face. second_face_score is NaN if no second face was detected.

In [85]:
birth_date = mat['wiki'][0][0][0][0].tolist()
photo_take_year = mat['wiki'][0][0][1][0].tolist()
file_path = mat['wiki'][0][0][2][0].tolist()
gender = mat['wiki'][0][0][3][0].tolist()
name = mat['wiki'][0][0][4][0].tolist()
face_loc = mat['wiki'][0][0][5][0].tolist()
face_score = mat['wiki'][0][0][6][0].tolist()
sec_face_score = mat['wiki'][0][0][7][0].tolist()

In [86]:
print( len( birth_date ) , len( photo_take_year ) , len( file_path ) , len( gender ) , len( name ) , len( face_loc ) , len( face_score ) , len( sec_face_score ))

62328 62328 62328 62328 62328 62328 62328 62328


In [119]:
t = np.array(face_loc)

In [120]:
t.shape

(62328, 1, 4)

In [121]:
t = t.reshape(62328,4)

In [122]:
face_loc = t.tolist()

In [123]:
meta_data = pd.DataFrame({"birth_date" : birth_date,
                         "photo_take_year" : photo_take_year,
                          "file_path" : file_path,
                          "gender" : gender,
                          "name" : name,
                          "face_loc" : face_loc,
                          "face_score" : face_score,
                          "sec_face_score" : sec_face_score
                         })

In [124]:
meta_data

birth_date  photo_take_year                          file_path  gender  \
0          723671             2009  [17/10000217_1981-05-05_2009.jpg]     1.0   
1          703186             1964  [48/10000548_1925-04-04_1964.jpg]     1.0   
2          711677             2008    [12/100012_1948-07-03_2008.jpg]     1.0   
3          705061             1961  [65/10001965_1930-05-23_1961.jpg]     1.0   
4          720044             2012  [16/10002116_1971-05-31_2012.jpg]     0.0   
...           ...              ...                                ...     ...   
62323      707582             1963   [49/9996949_1937-04-17_1963.jpg]     1.0   
62324      711338             1970   [32/9997032_1947-07-30_1970.jpg]     1.0   
62325      720620             2013   [09/9998109_1972-12-27_2013.jpg]     1.0   
62326      723893             2011   [00/9999400_1981-12-13_2011.jpg]     1.0   
62327      713846             2008    [80/999980_1954-06-11_2008.jpg]     0.0   

                         name  \
0           [Sami Jauhojärvi]   
1            [Dettmar Cramer]   
2               [Marc Okrand]   
3      [Aleksandar Matanović]   
4              [Diana Damrau]   
...                       ...   
62323             [Guus Haak]   
62324         [Nico Rijnders]   
62325     [Michael Wiesinger]   
62326        [Johann Grugger]   
62327    [Greta Van Susteren]   

                                                face_loc  face_score  \
0      [111.29109473290997, 111.29109473290997, 252.6...    4.300962   
1      [252.48330229530742, 126.68165114765371, 354.5...    2.645639   
2            [113.52, 169.83999999999997, 366.08, 422.4]    4.329329   
3                               [1.0, 1.0, 634.0, 440.0]        -inf   
4      [171.61031405173117, 75.57451239763239, 266.76...    3.408442   
...                                                  ...         ...   
62323  [128.92773553879837, 128.92773553879837, 320.1...    4.029268   
62324                           [1.0, 1.0, 285.0, 440.0]        -inf   
62325  [169.88839785556354, 74.31669471981023, 235.25...    3.494303   
62326                               [1.0, 1.0, 1.0, 1.0]        -inf   
62327  [92.72633234774001, 62.04355489849334, 230.120...    5.486917   

       sec_face_score  
0                 NaN  
1            1.949248  
2                 NaN  
3                 NaN  
4                 NaN  
...               ...  
62323             NaN  
62324             NaN  
62325             NaN  
62326             NaN  
62327             NaN  

[62328 rows x 8 columns]

In [130]:
meta_data.to_csv("Dataset\wiki_crop\wiki_meta_data.csv" , index=False)